source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir: ./_data

encoding:     "utf-8"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
url: ""

title: Raul Rodriguez
description: Software Engineer
google_analytics:
theme: jekyll-theme-cayman

github:
  owner_name: Raul Rodriguez
  owner_url: https://github.com/raulra08/
  repository_name: raulra08.github.io

include: ['_pages']
